name: sertinary
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0-119.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_icons: ^2.0.0
  auto_route: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_core: ^1.17.0
  firebase_analytics: ^9.1.8
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  google_fonts: ^2.3.2
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/
