name: sertinary
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0-119.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  animate_icons: ^2.0.0
  google_fonts: ^3.0.1

  auto_route: ^4.0.1

  firebase_core: ^1.17.0
  firebase_analytics: ^9.1.8
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  firebase_storage: ^10.2.17
  gradient_borders: ^0.2.0
  image_picker: ^0.8.5+3
  like_button: ^2.0.4
  hexagon: ^0.2.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/
